elements = {
    {
        number = 1,
        symbol = "H",
        name = "Hydrogen",
        conf_short = "1s1",
        conf_full = "1s1",
        shells = { 1 },
    },
    {
        number = 2,
        symbol = "He",
        name = "Helium",
        conf_short = "1s2",
        conf_full = "1s2",
        shells = { 2 },
    },
    {
        number = 3,
        symbol = "Li",
        name = "Lithium",
        conf_short = "[He] 2s1",
        conf_full = "1s2 2s1",
        shells = { 2, 1 },
    },
    {
        number = 4,
        symbol = "Be",
        name = "Beryllium",
        conf_short = "[He] 2s2",
        conf_full = "1s2 2s2",
        shells = { 2, 2 },
    },
    {
        number = 5,
        symbol = "B",
        name = "Boron",
        conf_short = "[He] 2s2 2p1",
        conf_full = "1s2 2s2 2p1",
        shells = { 2, 3 },
    },
    {
        number = 6,
        symbol = "C",
        name = "Carbon",
        conf_short = "[He] 2s2 2p2",
        conf_full = "1s2 2s2 2p2",
        shells = { 2, 4 },
    },
    {
        number = 7,
        symbol = "N",
        name = "Nitrogen",
        conf_short = "[He] 2s2 2p3",
        conf_full = "1s2 2s2 2p3",
        shells = { 2, 5 },
    },
    {
        number = 8,
        symbol = "O",
        name = "Oxygen",
        conf_short = "[He] 2s2 2p4",
        conf_full = "1s2 2s2 2p4",
        shells = { 2, 6 },
    },
    {
        number = 9,
        symbol = "F",
        name = "Fluorine",
        conf_short = "[He] 2s2 2p5",
        conf_full = "1s2 2s2 2p5",
        shells = { 2, 7 },
    },
    {
        number = 10,
        symbol = "Ne",
        name = "Neon",
        conf_short = "[He] 2s2 2p6",
        conf_full = "1s2 2s2 2p6",
        shells = { 2, 8 },
    },
    {
        number = 11,
        symbol = "Na",
        name = "Sodium",
        conf_short = "[Ne] 3s1",
        conf_full = "1s2 2s2 2p6 3s1",
        shells = { 2, 8, 1 },
    },
    {
        number = 12,
        symbol = "Mg",
        name = "Magnesium",
        conf_short = "[Ne] 3s2",
        conf_full = "1s2 2s2 2p6 3s2",
        shells = { 2, 8, 2 },
    },
    {
        number = 13,
        symbol = "Al",
        name = "Aluminum",
        conf_short = "[Ne] 3s2 3p1",
        conf_full = "1s2 2s2 2p6 3s2 3p1",
        shells = { 2, 8, 3 },
    },
    {
        number = 14,
        symbol = "Si",
        name = "Silicon",
        conf_short = "[Ne] 3s2 3p2",
        conf_full = "1s2 2s2 2p6 3s2 3p2",
        shells = { 2, 8, 4 },
    },
    {
        number = 15,
        symbol = "P",
        name = "Phosphorus",
        conf_short = "[Ne] 3s2 3p3",
        conf_full = "1s2 2s2 2p6 3s2 3p3",
        shells = { 2, 8, 5 },
    },
    {
        number = 16,
        symbol = "S",
        name = "Sulfur",
        conf_short = "[Ne] 3s2 3p4",
        conf_full = "1s2 2s2 2p6 3s2 3p4",
        shells = { 2, 8, 6 },
    },
    {
        number = 17,
        symbol = "Cl",
        name = "Chlorine",
        conf_short = "[Ne] 3s2 3p5",
        conf_full = "1s2 2s2 2p6 3s2 3p5",
        shells = { 2, 8, 7 },
    },
    {
        number = 18,
        symbol = "Ar",
        name = "Argon",
        conf_short = "[Ne] 3s2 3p6",
        conf_full = "1s2 2s2 2p6 3s2 3p6",
        shells = { 2, 8, 8 },
    },
}

return elements
